services:
  rabbitmq:
    build: 
      context: .
      dockerfile: Dockerfile
    image: rabbitmq:3-management
    container_name: rabbitmq_beaver_test_container
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_LOG_LEVEL=debug
      # - RABBITMQ_DEFAULT_USER=Admin
      # - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    # networks:
    #   - rabbitmq_network

volumes:
  rabbitmq_data:

# networks:
#   rabbitmq_network:
#     driver: bridge